/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Master Configuration
         * @description The whole composed conversation (root + navigator + every journey).
         */
        get: operations["master_configuration_configuration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/configuration/{journey_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Journey Configuration */
        get: operations["journey_configuration_configuration__journey_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Journey */
        post: operations["create_journey_journeys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys/{journey_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Journey */
        get: operations["get_journey_journeys__journey_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys/{journey_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Answer */
        post: operations["submit_answer_journeys__journey_id__answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys/{journey_id}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload File */
        post: operations["upload_file_journeys__journey_id__uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys/{journey_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Journey */
        post: operations["complete_journey_journeys__journey_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys/{journey_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Timeline */
        get: operations["get_timeline_journeys__journey_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerIn */
        AnswerIn: {
            /** Questionid */
            questionId: string;
            /**
             * Value
             * @description Answer value: string, number, array, or group object.
             */
            value: unknown;
        };
        /** AnswerResultOut */
        AnswerResultOut: {
            /**
             * Journeyid
             * Format: uuid
             */
            journeyId: string;
            /** Status */
            status: string;
            /** Currentnodeid */
            currentNodeId: string | null;
            /** Currentquestion */
            currentQuestion: {
                [key: string]: unknown;
            } | null;
            /** Completionpct */
            completionPct: number;
        };
        /** Body_upload_file_journeys__journey_id__uploads_post */
        Body_upload_file_journeys__journey_id__uploads_post: {
            /** Questionid */
            questionId?: string | null;
            /** File */
            file: string;
        };
        /** CompleteResultOut */
        CompleteResultOut: {
            /**
             * Journeyid
             * Format: uuid
             */
            journeyId: string;
            /** Status */
            status: string;
            /** Outcome */
            outcome: string;
            /**
             * Crmeventid
             * Format: uuid
             */
            crmEventId: string;
            /** Leadscore */
            leadScore: number;
            /** Emailsqueued */
            emailsQueued: number;
            /** Confirmation */
            confirmation: {
                [key: string]: unknown;
            };
        };
        /** ConfigurationOut */
        ConfigurationOut: {
            /** Journeykey */
            journeyKey: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Journeytype */
            journeyType: string | null;
            /** Flow */
            flow: {
                [key: string]: unknown;
            };
            /** Questions */
            questions: {
                [key: string]: unknown;
            };
            /** Confirmation */
            confirmation: {
                [key: string]: unknown;
            };
            /** Intro */
            intro: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** JourneyCreateIn */
        JourneyCreateIn: {
            /**
             * Journeykey
             * @description Journey key, e.g. 'employer'. Discovered from configuration.
             */
            journeyKey: string;
            /**
             * Leadsource
             * @description Attribution source (utm, referrer…).
             */
            leadSource?: string | null;
        };
        /** JourneyStateOut */
        JourneyStateOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Journeykey */
            journeyKey: string;
            /** Status */
            status: string;
            /** Currentnodeid */
            currentNodeId: string | null;
            /** Currentquestion */
            currentQuestion: {
                [key: string]: unknown;
            } | null;
            /** Currentstep */
            currentStep: number;
            /** Totalsteps */
            totalSteps: number;
            /** Completionpct */
            completionPct: number;
        };
        /** MasterConfigurationOut */
        MasterConfigurationOut: {
            /** Version */
            version: string;
            /** Intro */
            intro: {
                [key: string]: unknown;
            };
            /** Navigator */
            navigator: {
                [key: string]: unknown;
            };
            /** Flow */
            flow: {
                [key: string]: unknown;
            };
            /** Questions */
            questions: {
                [key: string]: unknown;
            };
            /** Journeys */
            journeys: {
                [key: string]: unknown;
            }[];
        };
        /** ReadyOut */
        ReadyOut: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /** Configuration */
            configuration: string;
            /** Journeys */
            journeys: number;
        };
        /** TimelineEventOut */
        TimelineEventOut: {
            /** Type */
            type: string;
            /** Label */
            label: string;
            /**
             * Occurredat
             * Format: date-time
             */
            occurredAt: string;
            /** Verificationstatus */
            verificationStatus: string;
            /** Visibility */
            visibility: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            } | null;
        };
        /** UploadOut */
        UploadOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Questionid */
            questionId: string | null;
            /** Filename */
            filename: string;
            /** Contenttype */
            contentType: string;
            /** Sizebytes */
            sizeBytes: number;
            /** Sha256 */
            sha256: string | null;
            /** Scanstatus */
            scanStatus: string;
            /** Provider */
            provider: string;
            /** Url */
            url: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
        };
    };
    master_configuration_configuration_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasterConfigurationOut"];
                };
            };
        };
    };
    journey_configuration_configuration__journey_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journey_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigurationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_journey_journeys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JourneyCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_journey_journeys__journey_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journey_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answer_journeys__journey_id__answers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journey_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_journeys__journey_id__uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journey_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_journeys__journey_id__uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_journey_journeys__journey_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journey_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_timeline_journeys__journey_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journey_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
